apiVersion: v1
kind: Service
metadata:
  name: devops-bookstore-api-service
  labels:
    app: devops-bookstore-api
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: devops-bookstore-api